apiVersion: apps/v1
kind: Deployment
metadata:
  name: zingle
  labels:
    app: zingle
spec:
  selector:
    matchLabels:
      app: zingle
  template:
    metadata:
      labels:
        app: zingle
    spec:
      containers:
      - name: zingle
        image: docker.io/library/php_php:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
      initContainers:
      - name: init-zingle-perms
        image: docker.io/library/php_php:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "ls -ald /opt/app-root/src/bootstrap/cache"]
      - name: init-zingle-user
        image: docker.io/library/php_php:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "id -u default; id -g default"]
