apiVersion: v1
kind: Service
metadata:
  name: zingle
spec:
  selector:
    app: minimal
  ports:
  - port: 9000
    targetPort: 9000
    name: fastcgi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: minimal
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: maria
spec:
  selector:
    app: minimal
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: elastic7
spec:
  selector:
    app: minimal
  ports:
  - port: 9200
    targetPort: 9200
